module.exports.policies = {
  '*': false,                       
  health: true,
  'customer/register': true,        
  'customer/login': true,
  'customer/forgot-pin': true,
  'customer/reset-pin': true,
  'officer/login': true,

  me: 'isAuthenticated',
  'customer/balance': 'isAuthenticated',
  'customer/instruments': 'isAuthenticated',
  'customer/history': 'isAuthenticated',
  'customer/billers': 'isAuthenticated',
  services: 'isAuthenticated',
  'txn/request': 'isAuthenticated',
  'txn/confirm': 'isAuthenticated',
  'txn/verify': 'isAuthenticated',
  'txn/callback': true,                  

  'mock/vcb': true,
  'mock/napas': true,
  'mock/visa': true,
  'mock/biller': true,

  'admin/services': ['isAuthenticated', 'isOfficer'],
  'admin/upsert-service': ['isAuthenticated', 'isOfficer'],
  'admin/toggle-service': ['isAuthenticated', 'isOfficer'],
  'admin/wallets': ['isAuthenticated', 'isOfficer'],
  'admin/create-wallet': ['isAuthenticated', 'isOfficer'],
  'admin/billers': ['isAuthenticated', 'isOfficer'],
  'admin/upsert-biller': ['isAuthenticated', 'isOfficer'],
  'admin/customers': ['isAuthenticated', 'isOfficer'],
  'admin/cash-in': ['isAuthenticated', 'isOfficer'],
  'admin/history': ['isAuthenticated', 'isOfficer'],
  'admin/test-connector': ['isAuthenticated', 'isOfficer'],
  'admin/upsert-connector': ['isAuthenticated', 'isOfficer'],
  'admin/toggle-connector': ['isAuthenticated', 'isOfficer'],
  'admin/delete-connector': ['isAuthenticated', 'isOfficer'],
  'admin/recover': ['isAuthenticated', 'isOfficer'],
  'admin/reconcile': ['isAuthenticated', 'isOfficer'],
  'admin/integrity': ['isAuthenticated', 'isOfficer'],
  'admin/trails': ['isAuthenticated', 'isOfficer'],
  'admin/connectors': ['isAuthenticated', 'isOfficer'],
};
