module.exports.routes = {
  'GET /api/health': { action: 'health' },

  'POST /api/customer/register': { action: 'customer/register' },
  'POST /api/customer/login':    { action: 'customer/login' },
  'POST /api/customer/forgot-pin': { action: 'customer/forgot-pin' },
  'POST /api/customer/reset-pin':  { action: 'customer/reset-pin' },
  'POST /api/officer/login':     { action: 'officer/login' },
  'GET  /api/me':                { action: 'me' },
  'GET  /api/customer/balance':  { action: 'customer/balance' },
  'GET  /api/customer/instruments': { action: 'customer/instruments' },
  'GET  /api/customer/history':     { action: 'customer/history' },
  'GET  /api/customer/billers':     { action: 'customer/billers' },
  'GET  /api/services':             { action: 'services' },

  // Engine 3 runtime 
  'POST /api/txn/request': { action: 'txn/request' },
  'POST /api/txn/confirm': { action: 'txn/confirm' },
  'POST /api/txn/verify':  { action: 'txn/verify' },
  'POST /api/txn/callback/:connector': { action: 'txn/callback' },

  'POST /mock/vcb/:op':   { action: 'mock/vcb' },
  'POST /mock/napas/:op': { action: 'mock/napas' },
  'POST /mock/visa/:op':  { action: 'mock/visa' },
  'POST /mock/biller/:op': { action: 'mock/biller' },

  'GET  /api/admin/services':       { action: 'admin/services' },
  'POST /api/admin/services/upsert': { action: 'admin/upsert-service' },
  'POST /api/admin/services/toggle': { action: 'admin/toggle-service' },
  'GET  /api/admin/wallets':        { action: 'admin/wallets' },
  'POST /api/admin/wallets/create': { action: 'admin/create-wallet' },
  'GET  /api/admin/billers':        { action: 'admin/billers' },
  'POST /api/admin/billers/upsert': { action: 'admin/upsert-biller' },
  'GET  /api/admin/customers':      { action: 'admin/customers' },
  'POST /api/admin/cash-in':        { action: 'admin/cash-in' },
  'GET  /api/admin/history':        { action: 'admin/history' },
  'POST /api/admin/connector/test': { action: 'admin/test-connector' },
  'POST /api/admin/connectors/upsert': { action: 'admin/upsert-connector' },
  'POST /api/admin/connectors/toggle': { action: 'admin/toggle-connector' },
  'POST /api/admin/connectors/delete': { action: 'admin/delete-connector' },
  'POST /api/admin/recover':        { action: 'admin/recover' },
  'GET  /api/admin/reconcile':      { action: 'admin/reconcile' },
  'GET  /api/admin/integrity':      { action: 'admin/integrity' },
  'GET  /api/admin/trails':         { action: 'admin/trails' },
  'GET  /api/admin/connectors':     { action: 'admin/connectors' },
};
